version: '3.8'

services:
  testtasktelros:
    container_name: testtasktelros
    build:
      context: .
      dockerfile: Dockerfile
    image: testtasktelros:latest
    ports:
      - "8085:8085"
    env_file: .env
    depends_on:
      - postgres


  postgres:
    image: postgres:17.2-alpine3.21
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: